version: '3'
 
services:
    database:
        image: postgres:13-alpine
        environment:
            POSTGRES_USER: main
            POSTGRES_PASSWORD: main
            POSTGRES_DB: main
        ports: [5432]
    
    phppgadmin:
        container_name: phppgadmin
        image: neimheadh/phppgadmin:latest
        ports: 
            - "10080:80"
        environment: 
            - POSTGRES_HOST=postgres
            - POSTGRES_PORT=5432
            - POSTGRES_USER=main
            - POSTGRES_PASSWORD=main